### ISSUE TITLE
ArtifactoryPath returns incorrect path if URL doesn't contain artifactory outside of domain

### ISSUE THREAD

**Issue by fuzzmz** [devopshq/artifactory#31] opened 2018-09-05 09:12 UTC
The `ArtifactoryPath` method returns an incorrect value if the string passed to it doesn't contain the word `artifactory` somewhere outside of the domain.

For example, if setting up Artifactory behind NGINX with a custom domain, then you have the following behavior:

```python
path = ArtifactoryPath("http://af.demo.local/gradle-ivy-local")
print(path)
```
Returns `http:/af.demo.local/gradle-ivy-local` (notice just the once forwards slash at the scheme level)

Using `path = ArtifactoryPath("http://artifactory.demo.local/gradle-ivy-local")` returns `http:/artifactory.demo.local/gradle-ivy-local` (still just one forward slash).

If you add `artifactory` somewhere in the URL (doesn't really matter where) then the path resolves correctly.

For example using `path = ArtifactoryPath("http://artifactory.demo.local/gradle-ivy-local/artifactory")` returns `http://artifactory.demo.local/gradle-ivy-local/artifactory`.

**Comment by fuzzmz** [comment] 2018-09-05 09:36
At a first glance looks like the error is coming from somewhere inside `pathlib`. Hopefully I'll have more time to investigate.

**Comment by norpol** [comment] 2018-10-23 11:04
Interesting issue, sounds like some pathlib issue indeed.
Just out of curiosity:
What does `http://af.demo.local/api/application.wadl` report for you? Our initial artifactory nginx configuration was removing the `/artifactory/` at top-level, resulting in semi-working api access. Later I figured that even the `.wadl` was expecting `/artifactory/` to be existent. Overall their NGINX config examples are really bad.

**Comment by fuzzmz** [comment] 2018-10-23 12:35
@norpol, fun times. Looking in the `application.wadl` it does look like it's expecting `/artifactory/` to exist:

`<resources base="http://af.demo.local/artifactory/api/">`

Surprisingly (or fortunately) though I haven't run into any API issues yet.

**Comment by fuzzmz** [comment] 2018-10-23 14:31
Damn. Do you remember any examples? I'd like to open a support ticket with
JFrog to hopefully have it fixed, or at least acknowledged.

**Comment by norpol** [comment] 2018-10-23 14:45
Not sure anymore, but I'll let you know if I recall (I've quit the job where I was using Artifactory, so can't tell from the notes I had there).

**Comment by drnlm** [comment] 2019-01-18 08:47
This is due to the code in _ArtifactoryFlavour's splitroot implementation

It's possible to work around the issue by providing a suitable configuration file, but that isn;t always feasible, so it would be nice to make this behaviour more configurable.

**Comment by joelee2012** [comment] 2019-03-14 08:58
can someone fix this issue ?

**Comment by gsemet** [comment] 2019-03-15 14:19
Hello. I reproduce this issue:
```python
>>> arti = ArtifactoryPath(...)  # arti is valid
>>> repo = "myrepo"
>>> path = "path/to/my/folder/ending/by/artifactory"
>>> name  "artifact_name.ext"
>>> rpath = arti.joinpath(repo, path, name)
>>> rpath.open()
...
    with rpath.open() as fd:
  File ".../site-packages/artifactory.py", line 1058, in open
    return self._accessor.open(self)
  File ".../site-packages/artifactory.py", line 675, in open
    cert=pathobj.cert)
  File ".../site-packages/artifactory.py", line 477, in rest_get_stream
    res = session.get(url, stream=True, verify=verify, cert=cert)
  File ".../site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File ".../site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File ".../site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File ".../site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File ".../site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'path/to/my/folder/ending/by/artifactory/actifact_name.ext': No schema supplied. Perhaps you meant http://path/to/my/folder/ending/by/artifactory/actifact_name.ext?
```

Really looks like somewhere if the path contains an "artifactory" path (between two "/" I guess), it consider is as a full URL to artifactory server instead of a repo/path part and reuse the same server than the `arti` object.

When the path does not contain "artifactory" folder, this code works well.

**Comment by sebalaise** [comment] 2019-03-22 14:09
I added a fix for this issue:

`    def splitroot(self, part, sep=sep):
        """
        Splits path string into drive, root and relative path

        Uses '/artifactory/' as a splitting point in URI. Everything
        before it, including '/artifactory/' itself is treated as drive.
        The next folder is treated as root, and everything else is taken
        for relative path.
        
        Add-on: If URI doesn't have '/artifactory/', drive can be only the
        hostname part of URI. The next folder is treated as root, and 
        everything else is taken for relative path.
        """
        drv = ''
        root = ''

        base = get_global_base_url(part)
        if base and without_http_prefix(part).startswith(without_http_prefix(base)):
            mark = without_http_prefix(base).rstrip(sep) + sep
            parts = part.split(mark)
        else:
            # Begin Add-on
            parse_url = urllib3.util.parse_url(part)
            rest = parse_url.path
            if not rest or rest == sep:
                drv = part
                return drv, '', ''
            paths = rest.split(sep)
            path_1 = paths[1]
            if path_1 != 'artifactory':
                drv = parse_url.scheme + '://'+ parse_url.hostname
                rest = ''
                if len(paths) > 2:
                    for idx in range(2, len(paths)):
                        rest = rest + sep + paths[idx] if rest else paths[idx]
                    print(rest)
                return drv, sep + path_1 + sep, rest
            mark = sep + path_1 + sep
            # End Add-on
            parts = part.split(mark)

        if len(parts) >= 2:
            drv = parts[0] + mark.rstrip(sep)
            rest = sep + mark.join(parts[1:])
        elif part.endswith(mark.rstrip(sep)):
            drv = part
            rest = ''
        else:
            rest = part

        if not rest:
            return drv, '', ''

        if rest == sep:
            return drv, '', ''

        if rest.startswith(sep):
            root, _, part = rest[1:].partition(sep)
            root = sep + root + sep

        return drv, root, part
`
It's up to you to create a pull request with this kind of fix...

**Comment by tsal** [comment] 2019-04-04 17:38
Similar issue, using the Jfrog SaaS solution:

```
path = ArtifactoryPath("https://hostexample.jfrog.io/hostexample/repo-name", apikey="apikey_here")

print(path)
```

results in:

```
https:/hostexample.jfrog.io/hostexample/repo-name
```

Which makes walking the path impossible as request will reject that URL (and rightfully so).

**Comment by vicyap** [comment] 2019-04-04 20:18
I just submitted a PR. I've been running into this issue as well.

**Closed** 2019-04-06 04:38 UTC
Labels: help wanted
