### ISSUE TITLE
No support for Python3.12

### ISSUE THREAD

**Issue by orim-orca** [devopshq/artifactory#449] opened 2024-05-21 10:56 UTC
A lot of environments are already moving to Python3.12 and dohq artifactory does not support Python3.12

Main issue is the usage of pathlib._Flavour which is deprecated in Python3.12, which I'm not sure the usage of it here and how to rewrite

**Comment by ni-balexand** [comment] 2024-05-31 15:01
Looks like a duplicate of #430

**Comment by allburov** [comment] 2024-06-02 03:42
@ni-balexand yes, it's!

**Closed by allburov** 2024-06-02 03:42 UTC
