### ISSUE TITLE
artifactory_.find_permission_target error

### ISSUE THREAD

**Issue by kamuops** [devopshq/artifactory#222] opened 2021-03-05 14:36 UTC
method artifactory_.find_permission_target() is not accepting the **permission targets with the hypen (-) or underscore (_)** . We have all our permission targets in same format (using hypen), hence raising this issue.  . 

Traceback (most recent call last):
  File "jfrog.py", line 10, in <module>
    permission = artifactory_.find_permission_target("test-writers")
  File "/usr/local/lib/python3.6/site-packages/artifactory.py", line 1756, in find_permission_target
    if obj.read():
  File "/usr/local/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 154, in read
    self._read_response(response)
  File "/usr/local/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 832, in _read_response
    response["principals"]["users"]
  File "/usr/local/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 847, in _permissions_from_json
    name, new_permissions = cls._principal_parse(key, permissions)
  File "/usr/local/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 841, in _principal_parse
    return cls._principal_name_parse(name), cls._permissions_parse(permissions)
  File "/usr/local/lib/python3.6/site-packages/dohq_artifactory/admin.py", line 865, in _permissions_parse
    raise ValueError("Unknown permission {name}".format(name=permission))
ValueError: Unknown permission mxm

**Comment by zhan9san** [comment] 2021-08-19 10:53
I'll follow up this issue

**Comment by zhan9san** [comment] 2021-08-23 03:30
Hi @kamuops 

> raise ValueError("Unknown permission {name}".format(name=permission))
> ValueError: Unknown permission mxm

It seems this issue has been fixed in [Add missing 'mxm' and 'x' permissions ](https://github.com/zhan9san/artifactory/commit/c50ae34baeda714e9d6c30a4896dc6d0cc539fbf)

Could you please verify it in latest version?

**Comment by beliaev-maksim** [comment] 2021-09-01 19:30
@kamuops 
as @zhan9san said, the issue is not that you use hypen or any other symbol, but that artifactory had unsupported permission types. Since #220 'mxm' or 'x' were added, so now it should not throw an error

**Closed** 2021-09-08 09:29 UTC
Labels: help wanted
